### PR TITLE
Add Kokeria's emotes for labymod

### PR DESCRIPTION
**Pull request by ToggledX**
For chat emotes I think Kokeria's emotes are a good alternative allthough they do not work the same exactly, they are very similar. If something is wrong just tell me to change it, I'm not used to doing this stuff lol.

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
Thanks! Even if it's not exactly the same, seems like a great replacement. 

Can you replace the curseforge link you provide with https://www.curseforge.com/minecraft/mc-mods/chatemotes/files/all?filter-game-version=2020709689%3A5806. Since a lot of 1.8 mods aren't on curseforge, many users don't know how to navigate it and just press the top download button for the latest version.

Also, can you sort your name in the credits by alphabetical order? Other than that, looks great and I will merge when the fixes are made!

**Comment by ToggledX** [comment]
Yeah sorry for that, I fixed it, I'm new to stuff like this. Thank you.

**Comment by MicrocontrollersDev** [comment]
All good, thanks for the contribution!

**Comment by Zetvue** [comment]
based

**Pull request merged**
