### PR TITLE
grammar fixes in some places, added some replacements in others

### PR DESCRIPTION
**Pull request by RayDeeUx**
* d_utils.md: grammar + technicality
* feather.md: REDACTION's name highlight is very aggressive that it ends up applying to own messages
* hychat.md: fix markdown syntax and add intro sentence
* labymod.md: xander's evergreen has mem display
* lunar.md: grammar, capitalization, markdown syntax
* refrac_v4.md: add mod, reword sentence, fix one capitalization error
* sbreinvented.md: added mods
* sbcatia.md: replace 5zig with xander evergreen—even 5zig reborn has slowly discontinued

### CODE REVIEW

**Review by MicrocontrollersDev — APPROVED** [review]
not sure how i feel abt simplestats since im not sure whether it’s discontinued or not. i think nora said she’d update it eventually but idk if she plans on doing it anymore. but whatever that’s fine for now, think the mod works currently anyways. otherwise lgtm

**Comment by MicrocontrollersDev** [comment]
actually i also don’t know how redaction works for hitbox is it all mobs or can you let it be only dragon. and does f3+b need to be toggled

**Comment by Zetvue** [comment]
> actually i also don’t know how redaction works for hitbox is it all mobs or can you let it be only dragon. and does f3+b need to be toggled

I will ask wyvest about the first one. for f3+b, no

**Comment by Zetvue** [comment]
i will merge this though since this is goog

**Review by Zetvue — APPROVED** [review]

**Comment by RayDeeUx** [comment]
> not sure how i feel abt simplestats since im not sure whether it’s discontinued or not.

eh, last i checked it does its job well and has a github repo. also iirc mew/nora said in skyclient that there are plans on rewriting so it's not fully unsupported

ty zetvue for merge

**Pull request merged**
