### PR TITLE
Fixes and additions

### PR DESCRIPTION
**Pull request by Mqisty**
Added alternatives and fixed a couple things.

Also added myself to contributors because I think I'm supposed to.

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
feel free to add yourself to the list of contributors at the bottom of every list as well

**Comment by Mqisty** [comment]
i feel wrong doing that when ive barely added anything lol

**Comment by Zetvue** [comment]
> i feel wrong doing that when ive barely added anything lol

You are obligated to credit yourself for every little thing you do

**Comment by MicrocontrollersDev** [comment]
if you don’t do it i will 🔫

**Comment by Mqisty** [comment]
alright alright no need to get violent smh

**Comment by Mqisty** [comment]
i should do it in alphabetical order in the lists too correct?

**Comment by MicrocontrollersDev** [comment]
yes

**Comment by MicrocontrollersDev** [comment]
cool, thanks!

**Pull request merged**
