### PR TITLE
NEU 2.1 Fishing

### PR DESCRIPTION
**Pull request by Mqisty**
Added NEU link for fishing tracking in case of 2.1 release

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
thanks, and gg!

**Comment by Mqisty** [comment]
May have made a mistake I'll figure it out 👍

**Comment by MicrocontrollersDev** [comment]
yeah accidentally removed the neu fishing 😅

**Comment by Mqisty** [comment]
we dont talk about how dumb i am 👍

**Comment by MicrocontrollersDev** [comment]
my inbox talking about it tho lol

**Comment by Mqisty** [comment]
fuck you this shits embarrassing

**Comment by Mqisty** [comment]
can this even be merged if i deleted the fork

**Comment by MicrocontrollersDev** [comment]
yes

**Comment by MicrocontrollersDev** [comment]
why did bro name the branch `v1` 💀

**Comment by Mqisty** [comment]
i barely even knew how to make a branch stfu

**Comment by MicrocontrollersDev** [comment]
> i barely even knew how to make a branch stfu

I really taught you well look at you all grown up now how the time flies 😭

**Comment by Mqisty** [comment]
> I really taught you well look at you all grown up now how the time flies

a real groomer

**Comment by MicrocontrollersDev** [comment]
bruh

**Pull request merged**
