### PR TITLE
W-OVERFLOW’s WeatherChanger -> Salmon’s WeatherChanger

### PR DESCRIPTION
**Pull request by Scherso**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
you can also add yourself to the contributors lists (or i’ll just do it later when i remember)

**Comment by Scherso** [comment]
> you can also add yourself to the contributors lists (or i’ll just do it later when i remember)

eventually

**Comment by Zetvue** [comment]
shitass

**Comment by Scherso** [comment]
Excuse me?

**Comment by Zetvue** [comment]
shitass

**Comment by Scherso** [comment]
In what context?

**Comment by Zetvue** [comment]
shitass

**Comment by Zetvue** [comment]
oh right i forgot about this PR

**Pull request merged**
