### PR TITLE
A couple of additions & changes

### PR DESCRIPTION
**Pull request by KTrain5169**
List of changes:
* Special Zealot alert no longer requires a mod (skyblockaddons.md)
* Added 2 FAQs regarding Prism Launcher (prism_win.md). This could be copy & pasted to prism_mac.md & prism_gnu.md but I'm not familiar enough with those systems to confirm.
* Modrinth/Prism discord servers links added with (hopefully) clear instructions to only ask about stuff unrelated to the guide (modrinth_win.md, prism_gnu.md, prism_mac.md)
* Modrinth/Prism guides now have `%appdata%\.minecraft` instead of `C:\Users\USER\AppData\Roaming\.minecraft` to allow for copy and paste (modrinth_win.md, prism_win.md). May need clarification to users that %appdata% is a variable path (that's my name for it) and as such its intended behaviour is to open `C:\Users\USER\AppData\Roaming` but we will see. It may also be better to tell users to use the Windows dialog box to copy and paste, but again, lmk if that's required.
* Added KTrain5169 to contributors.md (hello!)

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
A few things:

- Not a big fan of the change to %appdata% instructions. The old one was definitely a lot of text and is not straight up not followable for many since AppData is a hidden file, but this new one feels like it's lacking critical information that people who don't know how to use their computers won't be able to follow. You say to copy and paste %appdata%/.minecraft but you never say where exactly to paste it, and a lot of people may not know the top bar can be typed in. I think the old win+r text was easier to follow in this regard, and just adding that section back would be much better. Also this is personal preference but %appdata% is a very useful folder for many programs and since Windows saves history, I think it would be better to make opening the .minecraft folder its own step (and also because I can see people forgetting the . or using a \ instead or something when typing it in if they don't paste).

- The prism_win guide received two new common issues, but they're not in the other guides. Please copy paste them over. If you're not sure the file paths for java for other OS's just leave out that line (also I'm assuming that line is because (x86) is from the Minecraft launcher?).

**Comment by KTrain5169** [comment]
> A few things:
> 
> * Not a big fan of the change to %appdata% instructions. The old one was definitely a lot of text and is not straight up not followable for many since AppData is a hidden file, but this new one feels like it's lacking critical information that people who don't know how to use their computers won't be able to follow. You say to copy and paste %appdata%/.minecraft but you never say where exactly to paste it, and a lot of people may not know the top bar can be typed in. I think the old win+r text was easier to follow in this regard, and just adding that section back would be much better. Also this is personal preference but %appdata% is a very useful folder for many programs and since Windows saves history, I think it would be better to make opening the .minecraft folder its own step (and also because I can see people forgetting the . or using a \ instead or something when typing it in if they don't paste).

Will improve on that, thanks for feedback. I was realising that people won't realise you can type in the top bar anyways so I was planning on changing that to Win + R.

> * The prism_win guide received two new common issues, but they're not in the other guides. Please copy paste them over. If you're not sure the file paths for java for other OS's just leave out that line (also I'm assuming that line is because (x86) is from the Minecraft launcher?).

The x86 is because those are 32-bit versions of Java, which cannot allocate more than 2GB of RAM as a limitation.
The C:\Users path is where the Minecraft Launcher's Java is installed, which is the `SkyClient Updater still fails to update my mods!` FAQ.

**Comment by KTrain5169** [comment]
> I think it would be better to make opening the .minecraft folder its own step (and also because I can see people forgetting the . or *using a \ instead or something when typing it in if they don't paste*).

It literally doesn't matter btw, Windows accepts either one.

**Comment by KTrain5169** [comment]
@MicrocontrollersDev should be fixed, please review.

**Comment by MicrocontrollersDev** [comment]
Seems reasonable, will merge once I'm back at my PC and can do a full review but looks fine at a glance

**Pull request merged**
