### PR TITLE
consisitientencny

### PR DESCRIPTION
**Pull request by Mqisty**
i feel like this is better but ill wait for you to merge or close idk

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
i’m not sure if dumb people will understand what latest means. i’m sure most people will tho idk i’ll think about it. then again chances are if they find themselves on the site they were probably directly linked to the page they need

**Comment by Mqisty** [comment]
> i’ll think about it. 

im just gonna revert the changes and then you can change it if you want since for some reason pushing to a branch changes it on the site

**Comment by MicrocontrollersDev** [comment]
https://github.com/MicrocontrollersDev/Alternatives/blob/main/.github/workflows/deploy.yml#L4C18-L4C18 yeah i see why

**Comment by Mqisty** [comment]
> https://github.com/MicrocontrollersDev/Alternatives/blob/main/.github/workflows/deploy.yml#L4C18-L4C18 yeah i see why

you want me to change it rn? since im already changing the shit back

**Comment by MicrocontrollersDev** [comment]
i was gonna but im not familiar with the syntax so if u know then go ahead

**Comment by Zetvue** [comment]
discussion is happening

**Comment by Mqisty** [comment]
addressed in recent commit

**Pull request closed without merging**
