### PR TITLE
Fixing BetterHurtCam and adding Contributions

### PR DESCRIPTION
**Pull request by ksharizard**
Sorry for another PR, but forgot to change the name of betterhurtcam and add my name to the contributions list.

### CODE REVIEW

**Comment by Deftu** [comment]
It's all good, no worries

**Comment by MicrocontrollersDev** [comment]
NOOOOO i just pushed a change to his pr

**Comment by Deftu** [comment]
> NOOOOO i just pushed a change to his pr

HAHAHAHAHA

**Comment by MicrocontrollersDev** [comment]
thanks for the pr, and yeah its the same mod, I had just forgotten that salmon took it off w-overflow and then I regex'd it. it never existed on polyfrost. whoops

**Pull request merged**
