### PR TITLE
grammar fixes, links, some additions, a lot of pain

### PR DESCRIPTION
**Pull request by Mqisty**
Fixed a lot of links pointing to the wrong place or places that just don't exist. Changed links for consistency, fixed some grammar and spelling errors. Made an addition or two.

This is probably the last one I'm doing, it's not worth it when I don't even think anyone uses this anymore. If I made any errors ping me in the Discord (Moisty#8076) and I'll fix them. Sorry if I did my brain died in the middle of doing this.

### CODE REVIEW

**Review by MicrocontrollersDev — APPROVED** [review]
yeah looks good. read through real quick on mobile while in the car in a white castle drive thru but it all seems fine. will merge on a double check later

**Comment by Mqisty** [comment]
thats so specific 💀

**Comment by MicrocontrollersDev** [comment]
first time at white castle i was excited

**Comment by Shiggy-dev** [comment]
drive thru

**Comment by Mqisty** [comment]
tell me if its any good i havent been there in forever smh

**Comment by MicrocontrollersDev** [comment]
for $2.99 wasn’t expecting much but still kinda mid ngl
edit: got a crispy chicken slider

**Comment by Mqisty** [comment]
ah so its still the same as 7 years ago

**Comment by MicrocontrollersDev** [comment]
ima be real with you i didn’t double check it but it’s 2:30 am and i gotta go to the bathroom

**Comment by Zetvue** [comment]
delightful conversation

**Comment by MicrocontrollersDev** [comment]
wait nevermind i think my crispy chicken slider was only like $1.50, which considering it was only chicken and cheese, is okay i for that price i guess idk id rather go to wendy’s or something you feel me

**Comment by Zetvue** [comment]
imagine big chain food

**Comment by Zetvue** [comment]
local is obviously better

**Comment by Mqisty** [comment]
the only big chains i go to are five guys and panda express

**Comment by MicrocontrollersDev** [comment]
ye i know but in terms of burgers i don’t really have local where i live but like i went to a restaurant a month ago or two and they had an impossible burger and i don’t usually eat beef but man that was pretty damn good shit had me flabbergasted bro i know it’s unhealthy right now but man that’s probably the future of meat shit was crazy

**Comment by Mqisty** [comment]
nah calling something the "future of meat" is crazy

**Comment by MicrocontrollersDev** [comment]
five guys pretty good but my family’s pretty much vegetarian (and as i said i very rarely eat beef. i’m not supposed to eat beef or any meat for that matter because of religion but i don’t care 👍👍) so we only get the mushroom burger or whatever the hell it is honestly pretty good you’d think it’d be shit but nah shit was bussin. panda express orange chicken got me like 😍😍 tho the mushroom chicken also killing it

**Comment by MicrocontrollersDev** [comment]
it’s the future of meat bro the meat industry is crazy rn it ain’t right how it is it’s gotta change but like ima keep eating meat tho because i don’t care about the ethics of it much like i’m not about to become vegan you know

**Comment by Mqisty** [comment]
bros a whole meat lover this is wild

**Comment by Zetvue** [comment]
[ddf.txt](https://github.com/MicrocontrollersDev/Alternatives/files/8920332/ddf.txt)

**Comment by MicrocontrollersDev** [comment]
nah bro i rarely eat meat im just saying shit but chicken and seafood where it’s at tbh

**Comment by Mqisty** [comment]
i dont get why people cant eat meat because of religion god does not care if you eat a cow, beef is good and not even god gonna stop me from eating it

**Comment by MicrocontrollersDev** [comment]
nah bro im hindu so like cows are like a symbol of god or something. and caste wise im in the highest so im supposed to not eat meat at all (except fish given certain conditions). but like i never cared for religion restrictions im doing what i want to do

**Comment by Zetvue** [comment]
muslim?

**Pull request merged**
