### PR TITLE
Add an SBA fork

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
Since I checked all the changes and tested the builds myself, I can say it's worthy of being on the list

https://github.com/Fix3dll/SkyblockAddons

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
id rather wait till an actual release is made public

**Comment by Jason54jg** [comment]
It will never be done the creators said he was not going to continue to maintain the mods

**Comment by MicrocontrollersDev** [comment]
closing in favor of https://github.com/Kuschel-Swein/smixer-mod

**Comment by Mqisty** [comment]
Smixer was added, make an issue or another pull request if you have something to add.

**Pull request closed without merging**
