### PR TITLE
prism but for linux

### PR DESCRIPTION
**Pull request by Shiggy-dev**

### CODE REVIEW

**Comment by Shiggy-dev** [comment]
_very_ jank but somehow it somehow works

**Comment by MicrocontrollersDev** [comment]
not sure if you already know but the part about transferring mods between instances is currently still windows

**Comment by Shiggy-dev** [comment]
its a draft pr for a reason

**Comment by MicrocontrollersDev** [comment]
that’s why i prefaced it with “not sure if you know or not”

**Pull request merged**
