### PR TITLE
Update RefractionV4.md

### PR DESCRIPTION
**Pull request by jitterdev**
url shortener redirects to malicious website, redirect to official website instead

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
where do you download the mod on there?

**Comment by Wyvest** [comment]
shouldn't we just use https://www.mediafire.com/file/lkq447zc0yolem5/HyStats-v3.0_%25281.8.9%2529.jar/file lol

**Comment by jitterdev** [comment]
@MicrocontrollersDev I couldn't find it to be honest, but what wyvest put also works

**Comment by MicrocontrollersDev** [comment]
yeah i’m fine with just using the mediafire link

**Comment by MicrocontrollersDev** [comment]
fixed in https://github.com/MicrocontrollersDev/Alternatives/commit/b5efc7b1d432be8e53db6c47fe07a1ddd03ebfdf

**Pull request closed without merging**
