### PR TITLE
lunar: add stuff

### PR DESCRIPTION
**Pull request by Zetvue**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
waiting on crosshairmod for this one

**Comment by Zetvue** [comment]
> waiting on crosshairmod for this one

can you at least reverse the crosshairmod part and merge everything else

**Comment by MicrocontrollersDev** [comment]
im fine with that

gimme a bit tho busy rn

**Comment by MicrocontrollersDev** [comment]
ty

**Pull request merged**
