### PR TITLE
added some mods, fixed my own mistakes

### PR DESCRIPTION
**Pull request by Mqisty**
uhhhhhh yeah just some changes i felt like doing because im bored 👍

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
chatting lets you change chat background color?

**Comment by Mqisty** [comment]
it does [yes](https://github.com/W-OVERFLOW/Chatting/releases/tag/v1.2.0)

**Comment by MicrocontrollersDev** [comment]
man i don’t even know the features of the mod i dev for (i committed two very important one line changes)

**Comment by MicrocontrollersDev** [comment]
seems fine will merge if you’re good with it (before you have to make another pr 💀)

**Comment by Mqisty** [comment]
ima double check it and let you know in like an hour

**Comment by Mqisty** [comment]
> man i don’t even know the features of the mod i dev for (i committed two very important one line changes)

those changes very well couldve saved the whole mod fr

**Comment by MicrocontrollersDev** [comment]
nah they did bumped up the IGN rating deadass

**Comment by MicrocontrollersDev** [comment]
leave a comment or whatever when you’re done

**Comment by Mqisty** [comment]
will do maam ✊ (not actually done btw)

**Comment by Mqisty** [comment]
alright im done i cant be bothered to look over every single thing

**Comment by MicrocontrollersDev** [comment]
can you make all the optifine links in feather 1.12 consistent, currently one of them links directly to a version and the rest to the optifine homepage. thanks

**Comment by Mqisty** [comment]
i didnt mean to commit that 🗿

**Comment by MicrocontrollersDev** [comment]
yeah ok

**Pull request merged**
