### PR TITLE
removed unnecessary stuff

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
yes, you all hate me, and yes, you want me gone

I would do more but I have Seminar homework…

**Comment by ghost** [comment]
bad git etiquette-rep

**Comment by De-Snail** [comment]
lol seminar homework fuckin highschooler

**Comment by MicrocontrollersDev** [comment]
this doesn’t fit with what i’m trying to accomplish. it’s easier to just explain on the guide rather than have to explain for every support ticket asking why the launcher is broken

**Comment by ghost** [comment]
lol “fuckin highschooler” on a profit-free project about Minecraft. minecraft.

**Comment by De-Snail** [comment]
you think i contribute anything here? I'm just here because I can talk shit about micro

**Comment by ghost** [comment]
> this doesn’t fit with what i’m trying to accomplish. it’s easier to just explain on the guide rather than have to explain for every support ticket asking why the launcher is broken

I see. I feel as though you could say “it just doesn’t work because Minecraft broke it” in place of that, and still leave out the whole explanation thing

**Comment by ghost** [comment]
> you think i contribute anything here? I'm just here because I can talk shit about micro

ltg was right

**Comment by MicrocontrollersDev** [comment]
i disagree, some people like to ask questions. rather not have to make another thing for that. and it’s also kind of a thing i do with my lists, this isn’t unique to prism

**Comment by ghost** [comment]
> i disagree, some people like to ask questions. rather not have to make another thing for that. and it’s also kind of a thing i do with my lists, this isn’t unique to prism

ah alr, sorry I kind of wrote the pr halfhazardly after seeing this pop up:
image

**Comment by De-Snail** [comment]
oh shit i forgot that micro's things get seen by the people outside of the one little server

**Comment by ghost** [comment]
oh yeah and if you guys in skyclient want to siphon me off then reset all your channels <3
https://www.youtube.com/watch?v=oNCoJ3L8dHY

**Pull request closed without merging**
