### PR TITLE
3d skin layers

### PR DESCRIPTION
**Pull request by Zetvue**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
will keep open till a 1.8 port is actually made

**Comment by MicrocontrollersDev** [comment]
~~so that i remember when the port is released: remove the 1.16.5 message and change the link to only show 1.8.9 releases~~
done

**Comment by MicrocontrollersDev** [comment]
currently the mod is still in beta and has a few issues. until these issues are either ironed out enough or the mod is in a full release state, this will stay open. in advance, thanks for the PR!

**Comment by tr7zw** [comment]
I'm open for help to get it into a final state(in regards to the light/glow issue). Lunar just took my mod and denied helping me with the 1.8 backport, so that was fun.

**Comment by Zetvue** [comment]
> I'm open for help to get it into a final state(in regards to the light/glow issue). Lunar just took my mod and denied helping me with the 1.8 backport, so that was fun.

quite sad

**Pull request closed without merging**
